### ISSUE TITLE
Jan 2 umbuntu error

### ISSUE THREAD

**Issue by kalcan83** [ninneman/mbgui#9]
kalcan83@kalcan83-posiedon:~/Downloads$ ./mbguiJan2.py
  File "./mbguiJan2.py", line 26
    def __init__(self, master = None):
      ^
IndentationError: expected an indented block
kalcan83@kalcan83-posiedon:~/Downloads$ ^C

**Comment by ninneman** [comment]
My best guess is that somehow the code got mangled when you downloaded it. The line 26 in mbgui is `import subprocess`, not what's quoted above, which is actually line 32.
